### PR TITLE
TWON-17166: Incorrect battery estimate

### PR DESCRIPTION
**Pull request by tpaschidis**
Reduce saw effect for devices with Murata chip

### CODE REVIEW

**Review by lluisdiaz — APPROVED** [review]
LGTM

**Comment by faragon2n** [comment]
Is this change only related to battery estimation, or also includes charge-related changes?

**Comment by tpaschidis** [comment]
> Is this change only related to battery estimation, or also includes charge-related changes?

The jumps in % are due to an estimation where the driver thinks that the battery is on relaxed state. Our battery curve is done with OCV values and not when battery is under load.
Disabling relaxed state means that there will not be any more "relaxed" state estimations and the % will be adjusted only when full charge conditions are reached (V>4.2V & I<70mA)

**Review by dnietotwonav — APPROVED** [review]

**Review by faragon2n — APPROVED** [review]
LGTM

**Pull request merged**
